name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ stable, nightly, 1.65.0 ]

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-audit
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-audit
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: cargo test --all-targets --all-features
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run audit
      run: cargo audit
